### ISSUE TITLE
Error running on AWS

### ISSUE THREAD

**Issue by jreason** [sw360cab/blog-serverless-imagemagick-layer#1]
Hi,

I have a docker container running AWS Linux 2.

I have followed your example and and successfully run the code in the container:

`$HOME/im/compiled/target/bin/convert --version`

I have zipped up the files and uploaded to Lamda as a layer.

However, when i run on lambda:

`/opt/bin/convert --version`

I get the following error:

> /opt/bin/convert: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory

When i run the following command on lambda:

`ldd /opt/bin/convert`

>  	linux-vdso.so.1 (0x00007fff34716000)
> 	libz.so.1 => /lib64/libz.so.1 (0x00007f12ed0ba000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f12ece9c000)
> 	libgomp.so.1 => not found
> 	libm.so.6 => /lib64/libm.so.6 (0x00007f12ecb5c000)
> 	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f12ec946000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00007f12ec59b000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f12ed2cf000)

It seems as though libgomp.so.1 is the only file missing?
The runtime environment i am using on lambda is: Node.js 12.x

**Comment by jreason** [comment]
For reference, i did try to install libtiff along with it so not sure if this has caused the issue?

```
wget -qO- http://download.osgeo.org/libtiff/tiff-4.0.10.tar.gz | tar xfvz -
cd tiff-4.0.10
./configure --disable-shared --disable-dependency-tracking --enable-static --prefix=$HOME/im/compiled/delegates
make && make install && cd ..
```

`--with-tiff=yes`

**Comment by sw360cab** [comment]
@jreason Wow, very intersting. Let me review for while why the static compilation of libtiff is not working. AFAIK you did good. You just need to find out why ImageMagick is not finding static version of libtiff while compling.
I suspect a matter of path resoultion.

**Comment by sw360cab** [comment]
I suspect the problem was that you tried to compile `libtiff` as basic libs (such as `libpng` and `libjpg`), however it requires more complex compilation (more or less like `libfreetype`).

I provide you with a complete [script including libtiff](https://gist.github.com/sw360cab/5cc799256de66eee2f33ac5ff0244cd7)

I also create a compiled zip for you with [IM compiled with libtiff and fully static dependencies](https://we.tl/t-12B0dt8OX7)

Let me know if it works.

**Comment by sw360cab** [comment]
@jreason Closing as not having updates on the proposed solution.
Feel free to re-open or to comment.
